### ISSUE TITLE
Display on Client Startup GUI instead of using `BdApi.alert()`

### ISSUE THREAD

**Issue by bqbbo** [lumauser/QuoteonStartup#2]
If possible, display the quote on the discord startup screen instead of an alert after the client starts.

*Or simply just find a better alternative to `Bp.Alert()`*

**Comment by bqbbo** [comment]
https://docs.betterdiscord.app/plugins/basics/dom

**Comment by lumauser** [comment]
```Bp.alert()``` looks like this for example. What do you think?
<img width="1437" alt="Screenshot 2024-01-30 at 4 28 32 PM" src="https://github.com/lumauser/QuoteonStartup/assets/91039519/81468330-a523-4572-a805-dbc2354f5437">

**Comment by bqbbo** [comment]
Yes, this works, but isn't the most ideal for "Quote On Startup" because Discord already started. I was thinking of using Discord's actual start menu GUI.

It seems like an annoyance to look at some random quote after Discord launches rather than looking at a quote waiting for Discord to launch.

**Comment by lumauser** [comment]
I mean there's already a "Did you know" section when it loads and I think people would even have barely time to look at the quote while loading. That's just what I think though.

**Comment by bqbbo** [comment]
Possibly make this a user-configurable option then? Default it to whatever, but I'd personally use the startup GUI when I obtain the plugin.

**Comment by lumauser** [comment]
> Possibly make this a user-configurable option then? Default it to whatever, but I'd personally use the startup GUI when I obtain the plugin.

That doesn't sound that bad of an idea. Maybe I can consider doing it like that.
